version: '2'
services:
  svenserver:
    image: mars:5000/svenserver
    ports:
      - "27015:27015"
      - "27015:27015/udp"
  hl2dmserver:
    image: mars:5000/hl2dmserver
    ports:
      - "27016:27015"
      - "27016:27015/udp"
  ui-for-docker:
    image: uifd/ui-for-docker
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

